# Generated by Django 4.1 on 2022-08-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_categories_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currencie'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction'},
        ),
    ]
