# Generated by Django 4.1 on 2022-08-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_categories_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amonut',
            new_name='amount',
        ),
    ]
